import { CodeWalkthrough, Step } from "@/components/visualizer/CodeWalkthrough"
import { SyntaxAnatomy, Token } from "@/components/visualizer/SyntaxAnatomy"
import { motion } from "framer-motion"

export default function GenericsVis() {
    const genericSyntax: Token[] = [
        { label: "Keyword", text: "fn", color: "keyword" },
        { label: "Name", text: "print_me", color: "identifier" },
        { label: "Generics", text: "<T>", color: "type", description: "Placeholder type T" },
        { label: "Param", text: "(val: T)", color: "identifier", description: "Parameter of type T" },
        { label: "Block", text: "{ ... }", color: "punctuation" },
    ]

    const steps: Step[] = [
        {
            title: "Syntax: Generic Placeholders",
            description: "Generics allow you to write code that works for any type. `T` is a placeholder that will be filled by the compiler.",
            code: `// T can be anything!
fn print_me<T>(val: T) {
    // ...
}`,
            highlightedLines: [2],
            visualComponent: <SyntaxAnatomy tokens={genericSyntax} />
        },
        {
            title: "Monomorphization (Phase 1)",
            description: "When you call a generic function with an `i32`, the compiler generates a specific version for `i32`.",
            code: `fn main() {
    print_me(42); // T becomes i32
}`,
            highlightedLines: [2],
            visualComponent: (
                <div className="flex flex-col items-center justify-center gap-6 h-full">
                    <div className="text-xs font-bold text-muted-foreground uppercase tracking-widest">Compiler Generation</div>
                    <motion.div 
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="p-4 rounded-lg border-2 border-blue-500 bg-blue-500/10 font-mono text-sm"
                    >
                        <div className="text-blue-400 font-bold mb-2">// Generated by compiler</div>
                        <div>fn print_me_i32(val: <span className="text-blue-400 font-bold underline">i32</span>) {"{ ... }"}</div>
                    </motion.div>
                </div>
            )
        },
        {
            title: "Monomorphization (Phase 2)",
            description: "If you then call it with a `&str`, the compiler generates ANOTHER version for `&str`. This is why Rust generics are fast: no runtime overhead!",
            code: `fn main() {
    print_me(42); 
    print_me("hello"); // T becomes &str
}`,
            highlightedLines: [3],
            visualComponent: (
                <div className="flex flex-col items-center justify-center gap-4 h-full">
                    <div className="text-xs font-bold text-muted-foreground uppercase tracking-widest">Compiler Output (Two Functions)</div>
                    <div className="p-3 rounded-lg border border-blue-500/30 bg-blue-500/5 font-mono text-xs opacity-50">
                        fn print_me_i32(val: i32) {"{ ... }"}
                    </div>
                    <motion.div 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="p-4 rounded-lg border-2 border-green-500 bg-green-500/10 font-mono text-sm"
                    >
                        <div className="text-green-400 font-bold mb-2">// Generated by compiler</div>
                        <div>fn print_me_str(val: <span className="text-green-400 font-bold underline">&str</span>) {"{ ... }"}</div>
                    </motion.div>
                </div>
            )
        }
    ]

    return <CodeWalkthrough steps={steps} title="Generics & Monomorphization" />
}
