import { useState } from "react"
import { motion } from "framer-motion"
import { Card } from "@/components/ui/card"
import { Package, Terminal, FileText, Database } from "lucide-react"

export function CargoVis() {
    const [activeFile, setActiveFile] = useState<'toml' | 'lock' | 'src'>('toml')

    return (
        <div className="space-y-6">
            <div className="grid grid-cols-3 gap-4">
                <button 
                    onClick={() => setActiveFile('toml')}
                    className={`p-4 rounded-xl border transition-all ${activeFile === 'toml' ? 'border-primary bg-primary/5 ring-1 ring-primary' : 'bg-card'}`}
                >
                    <FileText className="mx-auto mb-2 text-primary" />
                    <div className="text-xs font-bold">Cargo.toml</div>
                </button>
                <button 
                    onClick={() => setActiveFile('lock')}
                    className={`p-4 rounded-xl border transition-all ${activeFile === 'lock' ? 'border-primary bg-primary/5 ring-1 ring-primary' : 'bg-card'}`}
                >
                    <Database className="mx-auto mb-2 text-blue-500" />
                    <div className="text-xs font-bold">Cargo.lock</div>
                </button>
                <button 
                    onClick={() => setActiveFile('src')}
                    className={`p-4 rounded-xl border transition-all ${activeFile === 'src' ? 'border-primary bg-primary/5 ring-1 ring-primary' : 'bg-card'}`}
                >
                    <Package className="mx-auto mb-2 text-green-500" />
                    <div className="text-xs font-bold">src/</div>
                </button>
            </div>

            <Card className="min-h-[350px] overflow-hidden flex flex-col">
                <div className="bg-muted px-4 py-2 border-b flex justify-between items-center">
                    <span className="text-xs font-mono">{activeFile === 'toml' ? 'Cargo.toml' : activeFile === 'lock' ? 'Cargo.lock' : 'src/main.rs'}</span>
                    <Terminal className="w-3 h-3 opacity-50" />
                </div>
                <div className="p-6 font-mono text-sm flex-1 bg-slate-950 text-slate-300">
                    {activeFile === 'toml' && (
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                            <div className="text-blue-400">[package]</div>
                            <div>name = "my_app"</div>
                            <div>version = "0.1.0"</div>
                            <div>edition = "2021"</div>
                            <div className="mt-4 text-blue-400">[dependencies]</div>
                            <div>serde = <span className="text-green-400">"1.0"</span></div>
                            <div>tokio = {'{'} version = <span className="text-green-400">"1.0"</span>, features = [<span className="text-green-400">"full"</span>] {'}'}</div>
                        </motion.div>
                    )}
                    {activeFile === 'lock' && (
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                            <div className="text-muted-foreground opacity-50"># Generated by Cargo. DO NOT EDIT.</div>
                            <div className="mt-2">[[package]]</div>
                            <div>name = "serde"</div>
                            <div>version = "1.0.197"</div>
                            <div>checksum = "0x535...94c"</div>
                            <div className="mt-4">[[package]]</div>
                            <div>name = "tokio"</div>
                            <div>version = "1.36.0"</div>
                        </motion.div>
                    )}
                    {activeFile === 'src' && (
                        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                            <div className="text-purple-400">use</div> serde::Serialize;
                            <div className="mt-4 text-purple-400">fn</div> <span className="text-blue-400">main</span>() {"{"}
                            <div className="pl-4">println!(<span className="text-green-400">"Hello, Cargo!"</span>);</div>
                            <div>{"}"}</div>
                        </motion.div>
                    )}
                </div>
            </Card>

            <div className="p-4 bg-primary/10 border border-primary/20 rounded-xl text-xs text-center font-bold">
                Cargo handles building, dependency management, and distribution.
            </div>
        </div>
    )
}
